/*
  embedul.ar™ embedded systems framework - http://embedul.ar
  
  [STREAM driver] stm32 usart.

  Copyright 2018-2022 Santiago Germino
  <sgermino@embedul.ar> https://www.linkedin.com/in/royconejo

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/

#pragma once

#include "embedul.ar/source/core/device/stream.h"
#include "embedul.ar/source/arch/arm-cortex/stm32/hal.h"
#include "embedul.ar/source/core/cyclic.h"


struct STREAM_USART
{
    struct STREAM       device;
    struct CYCLIC       sendCb;
    struct CYCLIC       recvCb;
    // Allocated by CubeMX autogenerated code
    UART_HandleTypeDef  * huart;
};


void STREAM_USART1_Init (struct STREAM_USART *const U,
                         UART_HandleTypeDef *const Huart,
                         uint8_t *const InBuffer, const uint32_t InOctets,
                         uint8_t *const OutBuffer, const uint32_t OutOctets);
void STREAM_USART2_Init (struct STREAM_USART *const U,
                         UART_HandleTypeDef *const Huart,
                         uint8_t *const InBuffer, const uint32_t InOctets,
                         uint8_t *const OutBuffer, const uint32_t OutOctets);
void STREAM_USART3_Init (struct STREAM_USART *const U,
                         UART_HandleTypeDef *const Huart,
                         uint8_t *const InBuffer, const uint32_t InOctets,
                         uint8_t *const OutBuffer, const uint32_t OutOctets);
void STREAM_USART6_Init (struct STREAM_USART *const U,
                         UART_HandleTypeDef *const Huart,
                         uint8_t *const InBuffer, const uint32_t InOctets,
                         uint8_t *const OutBuffer, const uint32_t OutOctets);
