#pragma once

#include "embedul.ar/source/core/manager/input/profile.h"


#define INPUT_PROFILE_GP2_BIT_MAP       1
#define INPUT_PROFILE_GP2_BIT_ACTION    1
#define INPUT_PROFILE_GP2_RANGE_MAP     0


enum INPUT_PROFILE_GP2_Bit
{
    INPUT_PROFILE_GP2_Bit_Right,
    INPUT_PROFILE_GP2_Bit_Left,
    INPUT_PROFILE_GP2_Bit_Down,
    INPUT_PROFILE_GP2_Bit_Up,
    INPUT_PROFILE_GP2_Bit_Start,
    INPUT_PROFILE_GP2_Bit_Select,
    INPUT_PROFILE_GP2_Bit_A,
    INPUT_PROFILE_GP2_Bit_B,
    INPUT_PROFILE_GP2_Bit_C,
    INPUT_PROFILE_GP2_Bit_X,
    INPUT_PROFILE_GP2_Bit_Y,
    INPUT_PROFILE_GP2_Bit_Z,
    INPUT_PROFILE_GP2_Bit__COUNT
};


INPUT_PROFILE_STRUCT(GP2);
