BUILD_LIBS += 3rd_party/freertos

lpc4337jbd144_CFLAGS += -DBSS_SECTION_OSWRAP_FREERTOS_RUN_TASK_STACK='CC_Section(".bss.$$RamLoc40")'
lpc4337jbd144_CFLAGS += -DBSS_SECTION_OSWRAP_FREERTOS_MAIN_TASK_STACK='CC_Section(".bss.$$RamLoc40")'
