#
# embedul.ar™ embedded systems framework - http://embedul.ar
#
# stm32cube library.
#
# Copyright 2018-2022 Santiago Germino
# <sgermino@embedul.ar> https://www.linkedin.com/in/royconejo
#
# This software is provided 'as-is', without any express or implied
# warranty.  In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
# 1. The origin of this software must not be misrepresented; you must not
#    claim that you wrote the original software. If you use this software
#    in a product, an acknowledgment in the product documentation would be
#    appreciated but is not required.
# 2. Altered source versions must be plainly marked as such, and must not be
#    misrepresented as being the original software.
# 3. This notice may not be removed or altered from any source distribution.
#

$(call emb_need_var,TARGET_BSP)
$(call emb_need_var,CHIP_FAMILY)

$(call emb_declare_lib,$\
    STM32Cube,$\
	LIB_STM32CUBE,$\
	$(TARGET_BSP),$\
	)

CHIP_FAMILY_UC ?= $(shell echo $(CHIP_FAMILY) | tr f F)

CFLAGS += -DLIB_STM32CUBE
CFLAGS += -DSTM32_$(CHIP_FAMILY_UC)

LIB_STM32CUBE_HAL := $(LIB_STM32CUBE)/Drivers/STM32$(CHIP_FAMILY_UC)xx_HAL_Driver
LIB_STM32CUBE_CMSIS := $(LIB_STM32CUBE)/Drivers/CMSIS

CFLAGS += -I$(LIB_STM32CUBE_HAL)/Inc
CFLAGS += -I$(LIB_STM32CUBE_CMSIS)/Include
CFLAGS += -I$(LIB_STM32CUBE_CMSIS)/Device/ST/STM32$(CHIP_FAMILY_UC)xx/Include

# Microcontroller system and startup files
OBJS += $(LIB_STM32CUBE_CMSIS)/Device/ST/STM32$(CHIP_FAMILY_UC)xx/Source/Templates/system_stm32$(CHIP_FAMILY)xx.o
OBJS += $(LIB_STM32CUBE_CMSIS)/Device/ST/STM32$(CHIP_FAMILY_UC)xx/Source/Templates/gcc/startup_stm32$(CHIP_FAMILY)$(CHIP_MODEL)xx.o
    # FIXME: Not all startup files will end with a generic variant of "xx".
    # Some model variants in the F4 family (401, 410, 412) are specifically 
    # matched: "startup_stm32f401x{c|e}.s", "startup_stm32f410{c|r|t}x.s",
    # and "startup_stm32f412{c|r|v|z}x.s". A generic way to match CHIP_VARIANT
    # with existing files is preferred to select the proper one.

# (1): 'hal' or 'll'
# (2): driver name
define include_driver
    OBJS += $(LIB_STM32CUBE_HAL)/Src/stm32$(CHIP_FAMILY)xx_$(1)_$(2).o
endef

# Automatically enabling HAL modules
# $(if $(filter hal,$(1)),$(eval $(if $(findstring _,$(2)),,$(eval CFLAGS += -DHAL_$(shell echo $(2) | tr [:lower:] [:upper:])_MODULE_ENABLED))))
    # FIXME: Automation commented to avoid causing a redefinition warning on those already defined in stm32f4xx_hal_conf.h.
    #        It seems there is no way to get rid of that file being included on STM32CubeMX autogenerated code.
    #        Therefore, you have to specify exactly the same HAL/LL drivers as defined in stm32f4xx_hal_conf in
    #        LIB_STM32CUBE_HAL_DRIVERS/LIB_STM32CUBE_LL_DRIVERS.

ifdef LIB_STM32CUBE_HAL_DRIVERS
    $(call emb_info,Using HAL drivers '$(LIB_STM32CUBE_HAL_DRIVERS)')
    $(call emb_info,Using LL drivers '$(LIB_STM32CUBE_LL_DRIVERS)')

    # Remove duplicates
    LIB_STM32CUBE_HAL_DRIVERS := $(sort $(LIB_STM32CUBE_HAL_DRIVERS))
    LIB_STM32CUBE_LL_DRIVERS := $(sort $(LIB_STM32CUBE_LL_DRIVERS))

    CFLAGS += -DUSE_HAL_DRIVER

    # STM32F?xx HAL Drivers
    OBJS += $(LIB_STM32CUBE_HAL)/Src/stm32$(CHIP_FAMILY)xx_hal.o

    $(foreach name,$(LIB_STM32CUBE_HAL_DRIVERS),$(eval $(call include_driver,hal,$(name))))
    $(foreach name,$(LIB_STM32CUBE_LL_DRIVERS),$(eval $(call include_driver,ll,$(name))))
else
    $(call emb_info,Using no HAL/LL drivers)
endif
