#pragma once
// -----------------------------------------------------------------------------
// Automatically generated by utils/lpc_pll0.c on May 22 2021 03:14:05
// -----------------------------------------------------------------------------

#if (MODELINE_PCLK_KHZ == 63750)
    #if !defined PLL0_RFREQ
        #define PLL0_RFREQ 1500000
    #endif
    #if (PLL0_RFREQ == 1500000)
        // MSEL 85, NSEL 8, PSEL 2.
        #define PLL0_MDEC 0x1636
        #define PLL0_SELP 0x1F
        #define PLL0_SELI 0x28
        #define PLL0_SELR 0x0
        #define PLL0_PDEC 0x42
        #define PLL0_NDEC 0x2C
    #elif (PLL0_RFREQ == 750000)
        // MSEL 170, NSEL 16, PSEL 2.
        #define PLL0_MDEC 0x2DB0
        #define PLL0_SELP 0x1F
        #define PLL0_SELI 0x14
        #define PLL0_SELR 0x0
        #define PLL0_PDEC 0x42
        #define PLL0_NDEC 0x7A
    #elif (PLL0_RFREQ == 500000)
        // MSEL 255, NSEL 24, PSEL 2.
        #define PLL0_MDEC 0x2492
        #define PLL0_SELP 0x1F
        #define PLL0_SELI 0xC
        #define PLL0_SELR 0x0
        #define PLL0_PDEC 0x42
        #define PLL0_NDEC 0x1F
    #elif (PLL0_RFREQ == 375000)
        // MSEL 340, NSEL 32, PSEL 2.
        #define PLL0_MDEC 0x7914
        #define PLL0_SELP 0x1F
        #define PLL0_SELI 0x8
        #define PLL0_SELR 0x0
        #define PLL0_PDEC 0x42
        #define PLL0_NDEC 0xE4
    #else
        #error Unsupported PLL0 reference frequency (PLL0_RFREQ) for a pixel clock of 63750 KHz (MODELINE_PCLK_KHZ).
    #endif
#elif (MODELINE_PCLK_KHZ == 74250)
    #if !defined PLL0_RFREQ
        #define PLL0_RFREQ 1500000
    #endif
    #if (PLL0_RFREQ == 1500000)
        // MSEL 99, NSEL 8, PSEL 2.
        #define PLL0_MDEC 0xDED
        #define PLL0_SELP 0x1F
        #define PLL0_SELI 0x24
        #define PLL0_SELR 0x0
        #define PLL0_PDEC 0x42
        #define PLL0_NDEC 0x2C
    #elif (PLL0_RFREQ == 750000)
        // MSEL 198, NSEL 16, PSEL 2.
        #define PLL0_MDEC 0x76DA
        #define PLL0_SELP 0x1F
        #define PLL0_SELI 0x10
        #define PLL0_SELR 0x0
        #define PLL0_PDEC 0x42
        #define PLL0_NDEC 0x7A
    #elif (PLL0_RFREQ == 500000)
        // MSEL 297, NSEL 24, PSEL 2.
        #define PLL0_MDEC 0x53E5
        #define PLL0_SELP 0x1F
        #define PLL0_SELI 0xC
        #define PLL0_SELR 0x0
        #define PLL0_PDEC 0x42
        #define PLL0_NDEC 0x1F
    #elif (PLL0_RFREQ == 375000)
        // MSEL 396, NSEL 32, PSEL 2.
        #define PLL0_MDEC 0x1E76
        #define PLL0_SELP 0x1F
        #define PLL0_SELI 0x8
        #define PLL0_SELR 0x0
        #define PLL0_PDEC 0x42
        #define PLL0_NDEC 0xE4
    #else
        #error Unsupported PLL0 reference frequency (PLL0_RFREQ) for a pixel clock of 74250 KHz (MODELINE_PCLK_KHZ).
    #endif
#elif (MODELINE_PCLK_KHZ == 74500)
    #if !defined PLL0_RFREQ
        #define PLL0_RFREQ 1000000
    #endif
    #if (PLL0_RFREQ == 1000000)
        // MSEL 149, NSEL 12, PSEL 2.
        #define PLL0_MDEC 0x38ED
        #define PLL0_SELP 0x1F
        #define PLL0_SELI 0x18
        #define PLL0_SELR 0x0
        #define PLL0_PDEC 0x42
        #define PLL0_NDEC 0xC7
    #elif (PLL0_RFREQ == 500000)
        // MSEL 298, NSEL 24, PSEL 2.
        #define PLL0_MDEC 0x27CA
        #define PLL0_SELP 0x1F
        #define PLL0_SELI 0xC
        #define PLL0_SELR 0x0
        #define PLL0_PDEC 0x42
        #define PLL0_NDEC 0x1F
    #else
        #error Unsupported PLL0 reference frequency (PLL0_RFREQ) for a pixel clock of 74500 KHz (MODELINE_PCLK_KHZ).
    #endif
#else
    #error Unsupported pixel clock frequency (MODELINE_PCLK_KHZ).
#endif
